name       : libuv
version    : 1.20.3
release    : 2
source     :
    - https://github.com/libuv/libuv/archive/v1.20.3.tar.gz : 43a388687194a15d5f3cc1980d53c405020a3586254c620e5f3c4d241bb9da05
license    : MIT
component  : programming
homepage   : https://libuv.org
summary    : A multi-platform support library with a focus on asynchronous I/O
description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily
    developed for use by Node.js, but it's also used by Luvit, Julia, pyuv, and others.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    # tests 204 & 205 fail in the sandbox
    %make check || :
