name       : libuv
version    : 1.42.0
release    : 10
source     :
    - https://github.com/libuv/libuv/archive/refs/tags/v1.42.0.tar.gz : 371e5419708f6aaeb8656671f89400b92a9bba6443369af1bb70bcd6e4b3c764
homepage   : https://libuv.org
license    : MIT
component  : programming.library
summary    : A multi-platform support library with a focus on asynchronous I/O
description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily developed for use by Node.js, but it's also used by Luvit, Julia, pyuv, and others.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -f $installdir/usr/lib64/{pkgconfig/libuv-static.pc,*.a}
    rm -rf $installdir/usr/share
check      : |
    # tests 213 & 214 fail in the sandbox
    %ninja_check || :
