name       : libuv
version    : 1.33.1
release    : 7
source     :
    - https://github.com/libuv/libuv/archive/v1.33.1.tar.gz : 63794499bf5da1720e249d3fc14ff396b70b8736effe6ce5b4e47e0f3d476467
license    : MIT
component  : programming
homepage   : https://libuv.org
summary    : A multi-platform support library with a focus on asynchronous I/O
description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily
    developed for use by Node.js, but it's also used by Luvit, Julia, pyuv, and others.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    # tests 213 & 214 fail in the sandbox
    %make check || :
