name       : libuv
version    : 1.24.1
release    : 5
source     :
    - https://github.com/libuv/libuv/archive/v1.24.1.tar.gz : 0d026c8f68c4d7b7c59de8f485f262ac71c24e0f3a80d740a25d20edd2f2774e
license    : MIT
component  : programming
homepage   : https://libuv.org
summary    : A multi-platform support library with a focus on asynchronous I/O
description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily
    developed for use by Node.js, but it's also used by Luvit, Julia, pyuv, and others.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    # tests 213 & 214 fail in the sandbox
    %make check || :
